--------------------------------------------------------
--  파일이 생성됨 - 월요일-4월-27-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PDS
--------------------------------------------------------

  CREATE TABLE "PDS" 
   (	"PNO" NUMBER, 
	"WRITER" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(3500 BYTE), 
	"TITLE" VARCHAR2(150 BYTE), 
	"REGDATE" DATE DEFAULT sysdate, 
	"UPDATEDATE" DATE DEFAULT sysdate, 
	"VIEWCNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
REM INSERTING into PDS
SET DEFINE OFF;
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (1,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (2,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (3,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (4,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (5,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (6,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (7,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (8,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (9,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (10,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (11,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (12,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (13,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (14,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (15,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (16,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (17,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (18,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (19,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (20,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (21,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (22,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (23,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (24,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (25,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (26,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (27,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (28,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (29,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (30,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (31,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (32,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (33,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (34,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (35,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (36,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (37,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (38,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (39,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (40,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (41,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (42,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (43,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (44,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (45,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (46,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (47,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (48,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (49,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (50,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (51,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (52,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (53,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (54,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (55,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (56,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (57,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (58,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (59,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (60,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (61,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (62,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (63,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (64,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (65,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (66,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (67,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (68,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (69,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (70,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (71,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (72,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (73,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (74,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (75,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (76,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (77,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (78,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (79,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (80,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (81,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (82,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (83,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (84,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (85,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (86,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (87,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (88,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (89,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (90,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (91,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (92,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (93,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (94,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (95,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (96,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (97,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (98,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (99,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (100,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (101,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (102,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (103,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (104,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (105,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (106,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (107,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (108,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (109,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (110,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (111,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (112,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (113,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (114,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (115,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (116,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (117,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (118,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (119,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (120,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (121,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (122,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (123,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (124,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (125,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (126,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (127,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (128,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (129,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (130,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (131,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (132,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (133,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (134,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (135,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (136,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (137,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (138,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (139,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (140,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (141,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (142,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (143,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (144,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (145,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (146,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (147,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (148,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (149,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (150,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (151,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (152,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (153,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (154,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (155,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (156,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (157,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (158,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (159,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (160,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (161,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (162,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (163,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (164,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (165,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (166,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (167,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (168,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (169,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (170,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (171,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (172,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (173,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (174,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (175,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (176,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (177,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (178,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (179,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (180,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (181,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (182,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (183,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (184,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (185,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (186,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (187,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (188,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (189,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (190,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (191,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (192,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (408,'mama','<p><img src="/getImg.do?fileName=cd30d81d8f1541e685c878892eba4189.jpg" style="width: 506px;"><img src="/getImg.do?fileName=99ea4e3e5d8f4c2e9806033dd8c706ef.jpg" style="width: 506px;"><img src="/getImg.do?fileName=f964a696d67f4eef84fb5b1d3e902369.jpg" style="width: 506px;"><img src="/getImg.do?fileName=54622b077cc24b64a3ba0e444354ab29.jpg" style="width: 506px;"><img src="/getImg.do?fileName=f3a813f7f927483690e37df5c21f1968.jpg" style="width: 506px;"><br></p>','test제목3',to_date('20/04/27','YY/MM/DD'),to_date('20/04/27','YY/MM/DD'),10);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (404,'mama','<p><img src="/getImg.do?fileName=2321eef40aa74627b63403380031bc87.jpg" style="width: 506px;"><br></p>','test제목2',to_date('20/04/27','YY/MM/DD'),to_date('20/04/27','YY/MM/DD'),4);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (193,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (194,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (195,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (196,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (197,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (198,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (199,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (200,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (201,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (202,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (203,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (204,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (205,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (206,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (207,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (208,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (209,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (210,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (211,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (212,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (213,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (214,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (215,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (216,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (217,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (218,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (219,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (220,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (221,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (222,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (223,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (224,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (225,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (226,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (227,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (228,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (229,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (230,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (231,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (232,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (233,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (234,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (235,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (236,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (237,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (238,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (239,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (240,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (241,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (242,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (243,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (244,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (245,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (246,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (247,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (248,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (249,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (250,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (251,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (252,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (253,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (254,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (255,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (256,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (257,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (258,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (259,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (260,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (261,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (262,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (263,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (264,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (265,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (266,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (267,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (268,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (269,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (270,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (271,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (272,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (273,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (274,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (275,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (276,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (277,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (278,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (279,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (280,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (281,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (282,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (283,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (284,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (285,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (286,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (287,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (288,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (289,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (290,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (291,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (292,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (293,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (294,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (295,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (296,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (297,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (298,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (299,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (300,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (301,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (302,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (303,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (304,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (305,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (306,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (307,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (308,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (309,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (310,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (311,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (312,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (313,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (314,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (315,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (316,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (317,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (318,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (319,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (320,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (321,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (322,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (323,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (324,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (325,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (326,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (327,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (328,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (329,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (330,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (331,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (332,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (333,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (334,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (335,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (336,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (337,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (338,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (339,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (340,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (341,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (342,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (343,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (344,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (345,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (346,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (347,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (348,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (349,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (350,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (351,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (352,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (353,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (354,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (355,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (356,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (357,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (358,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (359,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (360,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (361,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (362,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (363,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (364,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (365,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (366,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (367,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (368,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (369,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (370,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (371,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (372,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (373,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (374,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (375,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (376,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (377,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (378,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (379,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (380,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (381,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (382,'mimi','mimi','mimi',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (383,'mama','mama','mama',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (384,'irene','irene','irene',to_date('20/04/24','YY/MM/DD'),to_date('20/04/24','YY/MM/DD'),0);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (406,'mama','<p><img src="/getImg.do?fileName=6bf305b0cd03493782534b7193ac0d11.jpg" style="width: 506px;"><br></p>','test제목',to_date('20/04/27','YY/MM/DD'),to_date('20/04/27','YY/MM/DD'),2);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (407,'mama','<p><img src="/getImg.do?fileName=0654ce5b48f249918eca3d9e912b26fd.jpg" style="width: 506px;"><br></p>','test제목2',to_date('20/04/27','YY/MM/DD'),to_date('20/04/27','YY/MM/DD'),6);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (409,'mama','<p><img src="/getImg.do?fileName=f8a6519126fa4c7c87d34b42d4f62e5a.jpg" style="width: 506px;"><br></p>','톰캣쓰',to_date('20/04/27','YY/MM/DD'),to_date('20/04/27','YY/MM/DD'),41);
Insert into PDS (PNO,WRITER,CONTENT,TITLE,REGDATE,UPDATEDATE,VIEWCNT) values (405,'mama','<p><img src="/getImg.do?fileName=b1719126308140b580365fb7a92cfec8.jpg" style="width: 506px;"><br></p>','test제목3',to_date('20/04/27','YY/MM/DD'),to_date('20/04/27','YY/MM/DD'),5);
--------------------------------------------------------
--  DDL for Index PDS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS_PK" ON "PDS" ("PNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  Constraints for Table PDS
--------------------------------------------------------

  ALTER TABLE "PDS" ADD CONSTRAINT "PDS_PK" PRIMARY KEY ("PNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL"  ENABLE;
  ALTER TABLE "PDS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "PDS" MODIFY ("PNO" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table PDS
--------------------------------------------------------
COMMIT;