--------------------------------------------------------
--  DDL for Table BONUS
--------------------------------------------------------

  CREATE TABLE "PC05"."BONUS" 
   (	"ENAME" VARCHAR2(10 BYTE), 
	"JOB" VARCHAR2(9 BYTE), 
	"SAL" NUMBER, 
	"COMM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Table BUYER
--------------------------------------------------------

  CREATE TABLE "PC05"."BUYER" 
   (	"BUYER_ID" CHAR(6 BYTE), 
	"BUYER_NAME" VARCHAR2(40 BYTE), 
	"BUYER_LGU" CHAR(4 BYTE), 
	"BUYER_BANK" VARCHAR2(40 BYTE), 
	"BUYER_BANKNO" VARCHAR2(40 BYTE), 
	"BUYER_BANKNAME" VARCHAR2(15 BYTE), 
	"BUYER_ZIP" CHAR(7 BYTE), 
	"BUYER_ADD1" VARCHAR2(100 BYTE), 
	"BUYER_ADD2" VARCHAR2(80 BYTE), 
	"BUYER_COMTEL" VARCHAR2(14 BYTE), 
	"BUYER_FAX" VARCHAR2(20 BYTE), 
	"BUYER_MAIL" VARCHAR2(40 BYTE), 
	"BUYER_CHARGER" VARCHAR2(10 BYTE), 
	"BUYER_TELEXT" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Table BUYPROD
--------------------------------------------------------

  CREATE TABLE "PC05"."BUYPROD" 
   (	"BUY_DATE" DATE, 
	"BUY_PROD" VARCHAR2(10 BYTE), 
	"BUY_QTY" NUMBER(10,0), 
	"BUY_COST" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "PC05"."CART" 
   (	"CART_MEMBER" VARCHAR2(15 BYTE), 
	"CART_NO" CHAR(13 BYTE), 
	"CART_PROD" VARCHAR2(10 BYTE), 
	"CART_QTY" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;

   COMMENT ON COLUMN "PC05"."CART"."CART_MEMBER" IS '회원ID';
   COMMENT ON COLUMN "PC05"."CART"."CART_NO" IS '주문번호';
   COMMENT ON COLUMN "PC05"."CART"."CART_PROD" IS '상품코드';
   COMMENT ON COLUMN "PC05"."CART"."CART_QTY" IS '수량';
   COMMENT ON TABLE "PC05"."CART"  IS '장바구니 정보 테이블';
--------------------------------------------------------
--  DDL for Table DEPT
--------------------------------------------------------

  CREATE TABLE "PC05"."DEPT" 
   (	"DEPTNO" NUMBER(2,0), 
	"DNAME" VARCHAR2(14 BYTE), 
	"LOC" VARCHAR2(13 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Table EMP
--------------------------------------------------------

  CREATE TABLE "PC05"."EMP" 
   (	"EMPNO" NUMBER(4,0), 
	"ENAME" VARCHAR2(10 BYTE), 
	"JOB" VARCHAR2(9 BYTE), 
	"MGR" NUMBER(4,0), 
	"HIREDATE" DATE, 
	"SAL" NUMBER(7,2), 
	"COMM" NUMBER(7,2), 
	"DEPTNO" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Table LPROD
--------------------------------------------------------

  CREATE TABLE "PC05"."LPROD" 
   (	"LPROD_ID" NUMBER(7,0), 
	"LPROD_GU" CHAR(4 BYTE), 
	"LPROD_NM" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "PC05"."MEMBER" 
   (	"MEM_ID" VARCHAR2(15 BYTE), 
	"MEM_PASS" VARCHAR2(15 BYTE), 
	"MEM_NAME" VARCHAR2(20 BYTE), 
	"MEM_REGNO1" CHAR(6 BYTE), 
	"MEM_REGNO2" CHAR(7 BYTE), 
	"MEM_BIR" DATE, 
	"MEM_ZIP" CHAR(7 BYTE), 
	"MEM_ADD1" VARCHAR2(100 BYTE), 
	"MEM_ADD2" VARCHAR2(80 BYTE), 
	"MEM_HOMETEL" VARCHAR2(14 BYTE), 
	"MEM_COMTEL" VARCHAR2(14 BYTE), 
	"MEM_HP" VARCHAR2(15 BYTE), 
	"MEM_MAIL" VARCHAR2(40 BYTE), 
	"MEM_JOB" VARCHAR2(40 BYTE), 
	"MEM_LIKE" VARCHAR2(40 BYTE), 
	"MEM_MEMORIAL" VARCHAR2(40 BYTE), 
	"MEM_MEMORIALDAY" DATE, 
	"MEM_MILEAGE" NUMBER(10,0), 
	"MEM_DELETE" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Table NO_EXISTS_TABLE
--------------------------------------------------------

  CREATE TABLE "PC05"."NO_EXISTS_TABLE" 
   (	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Table PROD
--------------------------------------------------------

  CREATE TABLE "PC05"."PROD" 
   (	"PROD_ID" VARCHAR2(10 BYTE), 
	"PROD_NAME" VARCHAR2(40 BYTE), 
	"PROD_LGU" CHAR(4 BYTE), 
	"PROD_BUYER" CHAR(6 BYTE), 
	"PROD_COST" NUMBER(10,0), 
	"PROD_PRICE" NUMBER(10,0), 
	"PROD_SALE" NUMBER(10,0), 
	"PROD_OUTLINE" VARCHAR2(100 BYTE), 
	"PROD_DETAIL" CLOB, 
	"PROD_IMG" VARCHAR2(40 BYTE), 
	"PROD_TOTALSTOCK" NUMBER(10,0), 
	"PROD_INSDATE" DATE, 
	"PROD_PROPERSTOCK" NUMBER(10,0), 
	"PROD_SIZE" VARCHAR2(20 BYTE), 
	"PROD_COLOR" VARCHAR2(20 BYTE), 
	"PROD_DELIVERY" VARCHAR2(255 BYTE), 
	"PROD_UNIT" VARCHAR2(6 BYTE), 
	"PROD_QTYIN" NUMBER(10,0), 
	"PROD_QTYSALE" NUMBER(10,0), 
	"PROD_MILEAGE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" 
 LOB ("PROD_DETAIL") STORE AS BASICFILE (
  TABLESPACE "TS_DBSQL" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SALGRADE
--------------------------------------------------------

  CREATE TABLE "PC05"."SALGRADE" 
   (	"GRADE" NUMBER, 
	"LOSAL" NUMBER, 
	"HISAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "PC05"."USERS" 
   (	"USERID" VARCHAR2(20 BYTE), 
	"USERNM" VARCHAR2(20 BYTE), 
	"PASS" VARCHAR2(100 BYTE), 
	"REG_DT" DATE, 
	"ALIAS" VARCHAR2(50 BYTE), 
	"ADDR1" VARCHAR2(50 BYTE), 
	"ADDR2" VARCHAR2(50 BYTE), 
	"ZIPCODE" VARCHAR2(5 BYTE), 
	"FILENAME" VARCHAR2(50 BYTE), 
	"REALFILENAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;

   COMMENT ON COLUMN "PC05"."USERS"."USERID" IS '사용자 아이디';
   COMMENT ON COLUMN "PC05"."USERS"."USERNM" IS '사용자 이름';
   COMMENT ON COLUMN "PC05"."USERS"."PASS" IS '비밀번호';
   COMMENT ON COLUMN "PC05"."USERS"."REG_DT" IS '사용자 등록일';
   COMMENT ON COLUMN "PC05"."USERS"."ALIAS" IS '별명';
   COMMENT ON COLUMN "PC05"."USERS"."ADDR1" IS '주소';
   COMMENT ON COLUMN "PC05"."USERS"."ADDR2" IS '상세주소';
   COMMENT ON COLUMN "PC05"."USERS"."ZIPCODE" IS '우편번호';
   COMMENT ON COLUMN "PC05"."USERS"."FILENAME" IS '업로드파일명';
   COMMENT ON COLUMN "PC05"."USERS"."REALFILENAME" IS '실제파일경로';
   COMMENT ON TABLE "PC05"."USERS"  IS '사용자';
--------------------------------------------------------
--  DDL for Index PK_BUYER
--------------------------------------------------------

  CREATE UNIQUE INDEX "PC05"."PK_BUYER" ON "PC05"."BUYER" ("BUYER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Index PK_BUYPROD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PC05"."PK_BUYPROD" ON "PC05"."BUYPROD" ("BUY_DATE", "BUY_PROD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Index PK_CART
--------------------------------------------------------

  CREATE UNIQUE INDEX "PC05"."PK_CART" ON "PC05"."CART" ("CART_NO", "CART_PROD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Index PK_LPROD
--------------------------------------------------------

  CREATE UNIQUE INDEX "PC05"."PK_LPROD" ON "PC05"."LPROD" ("LPROD_GU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Index PK_MEM_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PC05"."PK_MEM_ID" ON "PC05"."MEMBER" ("MEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Index PK_PROD_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "PC05"."PK_PROD_ID" ON "PC05"."PROD" ("PROD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Index PK_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "PC05"."PK_USER" ON "PC05"."USERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  Constraints for Table BUYER
--------------------------------------------------------

  ALTER TABLE "PC05"."BUYER" ADD CONSTRAINT "PK_BUYER" PRIMARY KEY ("BUYER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL"  ENABLE;
  ALTER TABLE "PC05"."BUYER" MODIFY ("BUYER_MAIL" NOT NULL ENABLE);
  ALTER TABLE "PC05"."BUYER" MODIFY ("BUYER_FAX" NOT NULL ENABLE);
  ALTER TABLE "PC05"."BUYER" MODIFY ("BUYER_COMTEL" NOT NULL ENABLE);
  ALTER TABLE "PC05"."BUYER" MODIFY ("BUYER_LGU" NOT NULL ENABLE);
  ALTER TABLE "PC05"."BUYER" MODIFY ("BUYER_NAME" NOT NULL ENABLE);
  ALTER TABLE "PC05"."BUYER" MODIFY ("BUYER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUYPROD
--------------------------------------------------------

  ALTER TABLE "PC05"."BUYPROD" ADD CONSTRAINT "PK_BUYPROD" PRIMARY KEY ("BUY_DATE", "BUY_PROD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL"  ENABLE;
  ALTER TABLE "PC05"."BUYPROD" MODIFY ("BUY_COST" NOT NULL ENABLE);
  ALTER TABLE "PC05"."BUYPROD" MODIFY ("BUY_QTY" NOT NULL ENABLE);
  ALTER TABLE "PC05"."BUYPROD" MODIFY ("BUY_PROD" NOT NULL ENABLE);
  ALTER TABLE "PC05"."BUYPROD" MODIFY ("BUY_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "PC05"."CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY ("CART_NO", "CART_PROD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL"  ENABLE;
  ALTER TABLE "PC05"."CART" MODIFY ("CART_QTY" NOT NULL ENABLE);
  ALTER TABLE "PC05"."CART" MODIFY ("CART_PROD" NOT NULL ENABLE);
  ALTER TABLE "PC05"."CART" MODIFY ("CART_NO" NOT NULL ENABLE);
  ALTER TABLE "PC05"."CART" MODIFY ("CART_MEMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "PC05"."EMP" MODIFY ("EMPNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LPROD
--------------------------------------------------------

  ALTER TABLE "PC05"."LPROD" ADD CONSTRAINT "PK_LPROD" PRIMARY KEY ("LPROD_GU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL"  ENABLE;
  ALTER TABLE "PC05"."LPROD" MODIFY ("LPROD_NM" NOT NULL ENABLE);
  ALTER TABLE "PC05"."LPROD" MODIFY ("LPROD_GU" NOT NULL ENABLE);
  ALTER TABLE "PC05"."LPROD" MODIFY ("LPROD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "PC05"."MEMBER" ADD CONSTRAINT "PK_MEM_ID" PRIMARY KEY ("MEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL"  ENABLE;
  ALTER TABLE "PC05"."MEMBER" MODIFY ("MEM_MAIL" NOT NULL ENABLE);
  ALTER TABLE "PC05"."MEMBER" MODIFY ("MEM_COMTEL" NOT NULL ENABLE);
  ALTER TABLE "PC05"."MEMBER" MODIFY ("MEM_HOMETEL" NOT NULL ENABLE);
  ALTER TABLE "PC05"."MEMBER" MODIFY ("MEM_ADD2" NOT NULL ENABLE);
  ALTER TABLE "PC05"."MEMBER" MODIFY ("MEM_ADD1" NOT NULL ENABLE);
  ALTER TABLE "PC05"."MEMBER" MODIFY ("MEM_ZIP" NOT NULL ENABLE);
  ALTER TABLE "PC05"."MEMBER" MODIFY ("MEM_REGNO2" NOT NULL ENABLE);
  ALTER TABLE "PC05"."MEMBER" MODIFY ("MEM_REGNO1" NOT NULL ENABLE);
  ALTER TABLE "PC05"."MEMBER" MODIFY ("MEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "PC05"."MEMBER" MODIFY ("MEM_PASS" NOT NULL ENABLE);
  ALTER TABLE "PC05"."MEMBER" MODIFY ("MEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROD
--------------------------------------------------------

  ALTER TABLE "PC05"."PROD" ADD CONSTRAINT "PK_PROD_ID" PRIMARY KEY ("PROD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL"  ENABLE;
  ALTER TABLE "PC05"."PROD" MODIFY ("PROD_PROPERSTOCK" NOT NULL ENABLE);
  ALTER TABLE "PC05"."PROD" MODIFY ("PROD_TOTALSTOCK" NOT NULL ENABLE);
  ALTER TABLE "PC05"."PROD" MODIFY ("PROD_IMG" NOT NULL ENABLE);
  ALTER TABLE "PC05"."PROD" MODIFY ("PROD_OUTLINE" NOT NULL ENABLE);
  ALTER TABLE "PC05"."PROD" MODIFY ("PROD_SALE" NOT NULL ENABLE);
  ALTER TABLE "PC05"."PROD" MODIFY ("PROD_PRICE" NOT NULL ENABLE);
  ALTER TABLE "PC05"."PROD" MODIFY ("PROD_COST" NOT NULL ENABLE);
  ALTER TABLE "PC05"."PROD" MODIFY ("PROD_BUYER" NOT NULL ENABLE);
  ALTER TABLE "PC05"."PROD" MODIFY ("PROD_LGU" NOT NULL ENABLE);
  ALTER TABLE "PC05"."PROD" MODIFY ("PROD_NAME" NOT NULL ENABLE);
  ALTER TABLE "PC05"."PROD" MODIFY ("PROD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "PC05"."USERS" ADD CONSTRAINT "PK_USER" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL"  ENABLE;
