--------------------------------------------------------
--  DDL for Table ATTACH
--------------------------------------------------------

  CREATE TABLE "JAVA"."ATTACH" 
   (	"ANO" NUMBER, 
	"UPLOADPATH" VARCHAR2(300 BYTE), 
	"FILENAME" VARCHAR2(300 BYTE), 
	"BNO" NUMBER, 
	"ATTACHER" VARCHAR2(50 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"FILETYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Index ATTATCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA"."ATTATCH_PK" ON "JAVA"."ATTACH" ("ANO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  Constraints for Table ATTACH
--------------------------------------------------------

  ALTER TABLE "JAVA"."ATTACH" ADD CONSTRAINT "ATTATCH_PK" PRIMARY KEY ("ANO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL"  ENABLE;
  ALTER TABLE "JAVA"."ATTACH" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."ATTACH" MODIFY ("UPLOADPATH" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."ATTACH" MODIFY ("ANO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ATTACH
--------------------------------------------------------

  ALTER TABLE "JAVA"."ATTACH" ADD CONSTRAINT "ATTACH_FK1" FOREIGN KEY ("BNO")
	  REFERENCES "JAVA"."BOARD" ("BNO") ON DELETE CASCADE ENABLE;
