--------------------------------------------------------
--  파일이 생성됨 - 화요일-4월-28-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PDS
--------------------------------------------------------

  CREATE TABLE "JAVA"."PDS" 
   (	"PNO" NUMBER, 
	"WRITER" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(3500 BYTE), 
	"TITLE" VARCHAR2(150 BYTE), 
	"REGDATE" DATE DEFAULT sysdate, 
	"UPDATEDATE" DATE DEFAULT sysdate, 
	"VIEWCNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  DDL for Index PDS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA"."PDS_PK" ON "JAVA"."PDS" ("PNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL" ;
--------------------------------------------------------
--  Constraints for Table PDS
--------------------------------------------------------

  ALTER TABLE "JAVA"."PDS" ADD CONSTRAINT "PDS_PK" PRIMARY KEY ("PNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DBSQL"  ENABLE;
  ALTER TABLE "JAVA"."PDS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."PDS" MODIFY ("PNO" NOT NULL ENABLE);
